---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-data
      name: nginx-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
    
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-letsencrypt
      name: nginx-letsencrypt
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-nginx
  namespace: $OKTETO_NS
  annotations:
    # dev.okteto.com/generate-host: "true"
spec:
  rules:
  - host: admin-nginx-$OKTETO_NS.cloud.okteto.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 81

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "81"
      port: 81
      targetPort: 81
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  # replicas: 1
  # SCALE TO 0
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/hcf-default: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: jc21/nginx-proxy-manager:latest
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 81
            - containerPort: 443
          resources:
            limits:
              cpu: 250m
              memory: "214748364"
          volumeMounts:
            - mountPath: /data
              name: nginx-data
            - mountPath: /etc/letsencrypt
              name: nginx-letsencrypt
      restartPolicy: Always
      subdomain: hcfmailing
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-data
        - name: nginx-letsencrypt
          persistentVolumeClaim:
            claimName: nginx-letsencrypt
status: {}
    