---
apiVersion: v1
kind: Secret
metadata:
  name: timestamp
  namespace: $OKTETO_NS
  labels:
    app.kubernetes.io/name: timestamp
    app.kubernetes.io/instance: timestamp
type: Opaque
stringData:
  timestamp: "$TIMESTAMP"
